services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-dev-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
      - LOG_LEVEL=DEBUG

volumes:
  static_volume:
  media_volume:
  sqlite_data: