# Generated by Django 6.0.5 on 2026-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('description', models.CharField(max_length=255, verbose_name='Описание скидки/акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий (Активен)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод и купон',
                'verbose_name_plural': 'Промокоды и купоны',
            },
        ),
    ]
