# Generated by Django 6.0.5 on 2026-05-20 11:21

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото новости'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18, validators=[cinema.models.validate_age]),
        ),
    ]
