# Generated by Django 6.0.5 on 2026-05-20 13:59

import cinema.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_userprofile_phone_userprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='rows_count',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество рядов'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество мест в ряду'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.PositiveIntegerField(editable=False, verbose_name='Вместимость (мест)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18, validators=[cinema.models.validate_age], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +375 (XX) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('showtime', 'row', 'seat'), name='unique_showtime_row_seat'),
        ),
    ]
