# Generated by Django 6.0.5 on 2026-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_ticket_unique_together_cinemahall_rows_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at_utc'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at_utc'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_time',
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (Минск)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (UTC)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (Минск)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения (UTC)'),
        ),
    ]
