# Generated by Django 6.0.5 on 2026-05-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_newsarticle_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactemployee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='contactemployee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_contact', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (сотрудник)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочий email'),
        ),
        migrations.AlterField(
            model_name='contactemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Вакансия открыта'),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
